### PR TITLE
Fix ADD ADD-ON REPOSITORY TO HA link

### PR DESCRIPTION
**Pull request by astritzeqiri**
ISSUE: [215](https://github.com/NSPManager/NSPanelManager/issues/215)

This fixes the "ADD ADD-ON REPOSITORY TO HA" link.

From: https://github.com/NSPanelManager%2NSPManager

To: https://github.com/NSPManager/NSPanelManager

image

### CODE REVIEW

**Comment by tpanajott** [comment]
Hi and thank you for your contribution, have you verified that this works? I do not run Home Assistant OS and can therefore not test it myself. I'm assuming you've tested it.

**Comment by astritzeqiri** [comment]
@tpanajott Yes it does. I tested it with that change, its basically just a broken link.
image

**Comment by tpanajott** [comment]
Thanks, just wanted confirmation. Thanks for your help, the docs are really new and not quite ready yet but hopefully soon.

**Comment by astritzeqiri** [comment]
Glad I could help. Thanks to you guys for creating this awesome project 🚀

**Pull request merged**
